[tool.poetry]
name = "yt_chat"
version = "0.1.0"
description = "A Flask application for summarizing YouTube videos and chatting with a bot."
authors = ["mcordier <matt.cordier@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^3.0.1"
youtube-transcript-api = "^0.6.2"
chromadb = "^0.4.22"
openai = "^1.14.3"
fastapi = "^0.110.0"
python-multipart = "^0.0.9"
joblib = "^1.4.0"
ollama = "^0.1.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
