[tool.poetry]
name = "yt-chat"
version = "0.1.0"
description = "A Flask application for summarizing YouTube videos and chatting with a bot."
authors = ["mcordier <matt.cordier@icloud.com>"]
readme = "README.md"
packages = [{include = "yt_chat"}]


[tool.poetry.dependencies]
python = "^3.9"
youtube-transcript-api = "^0.6.2"
openai = "^1.14.3"
joblib = "^1.4.0"
ollama = "^0.1.8"
qdrant-client = "^1.8.2"
chainlit = "^1.0.504"
tenacity = "^8.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
